title = "metadata for oscar CI run"

[env]
os = [ "ubuntu-24.04" ]
julia-version = [ "~1.10.0-0"]
# branches = [ "release", "<matching>" ]

[pkgs]
  [pkgs.Oscar]
  test = true

  [pkgs.Polymake]
  branches = []
  test = true

[include]
  [include.111]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.11"
  os = "ubuntu-latest"

  [include.nightly12]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.12-nightly"
  os = "ubuntu-latest"

  [include.nightly]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "nightly"
  os = "ubuntu-latest"

  [include.macaarch64]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.10"
  os = "macos-14"
