title = "metadata for oscar CI run"

[env]
os = [ ["Linux","RPTU","normal-memory"] ]
julia-version = [ "1.10"]
# branches = [ "release", "<matching>" ]

[pkgs]
  [pkgs.Oscar]
  test = true

  [pkgs.Polymake]
  branches = []
  test = true

[include]
  [include.111]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.11"
  os = ["Linux","RPTU","normal-memory"]

  [include.nightly12]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "~1.12.0-0"
  os = ["Linux","RPTU","normal-memory"]

  [include.nightly]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "nightly"
  os = ["Linux","RPTU","normal-memory"]

  [include.macaarch64]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.10"
  os = "macos-14"
