title = "metadata for oscar CI run"

[env]
os = [ "ubuntu-22.04" ]
julia-version = [ "~1.6.0-0", "~1.10.0-0"]
# branches = [ "release", "<matching>" ]

[pkgs]
  [pkgs.Oscar]
  test = true

  [pkgs.Polymake]
  branches = []
  test = true

[include]
  [include.111nightly]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.11-nightly"
  os = "ubuntu-latest"

  [include.nightly]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "nightly"
  os = "ubuntu-latest"

  [include.macamd64lts]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.6"
  os = "macos-13"

  [include.macaarch64]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "1.10"
  os = "macos-14"
